### ISSUE TITLE
Archive dropdown; tag cloud

### ISSUE THREAD

**Issue by morninj** [BTLJ/btlj.org#14]
Under "Journal Archives" (e.g., the right column on http://btlj.mornin.org/about/executive-and-editorial-board/), condense the list of years to a dropdown menu (i.e., a <select>). Then, to fill the space, let's add a tag cloud underneath it in the same column and let's see how it looks. Should be plenty of WP plugins for the tag cloud.

**Comment by amahani** [comment]
All set.
